"""SDLC gate engine: runs gates in order and records GO / CONDITIONAL GO / NO-GO decisions."""

from __future__ import annotations

import json
import time
from collections.abc import Callable
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT_JSON = ROOT / "reports" / "gate_report.json"
GATE_LOG_MD = ROOT / "docs" / "gate_log.md"


class Decision(StrEnum):
    GO = "GO"
    CONDITIONAL_GO = "CONDITIONAL GO"
    NO_GO = "NO-GO"
    NOT_RUN = "NOT RUN"


@dataclass(frozen=True)
class CheckResult:
    passed: bool
    evidence: str


@dataclass(frozen=True)
class Check:
    name: str
    run: Callable[[], CheckResult]
    blocking: bool = True


@dataclass(frozen=True)
class Gate:
    id: str
    phase: str
    deliverables: tuple[str, ...]
    checks: tuple[Check, ...]


@dataclass
class CheckOutcome:
    name: str
    blocking: bool
    passed: bool
    evidence: str
    seconds: float


@dataclass
class GateOutcome:
    id: str
    phase: str
    decision: Decision
    checks: list[CheckOutcome] = field(default_factory=list)
    timestamp: str = ""

    @property
    def advances(self) -> bool:
        return self.decision in (Decision.GO, Decision.CONDITIONAL_GO)


def evaluate_gate(gate: Gate) -> GateOutcome:
    outcome = GateOutcome(gate.id, gate.phase, Decision.GO,
                          timestamp=datetime.now(UTC).isoformat(timespec="seconds"))
    for check in gate.checks:
        start = time.perf_counter()
        try:
            result = check.run()
        except Exception as exc:  # a crashing check is a failed check, never a silent pass
            result = CheckResult(False, f"check raised {type(exc).__name__}: {exc}")
        outcome.checks.append(CheckOutcome(check.name, check.blocking, result.passed,
                                           result.evidence, round(time.perf_counter() - start, 2)))

    if any(c.blocking and not c.passed for c in outcome.checks):
        outcome.decision = Decision.NO_GO
    elif any(not c.passed for c in outcome.checks):
        outcome.decision = Decision.CONDITIONAL_GO
    return outcome


def load_previous() -> dict[str, dict]:
    if REPORT_JSON.exists():
        return {g["id"]: g for g in json.loads(REPORT_JSON.read_text())["gates"]}
    return {}


def run_gates(gates: list[Gate], start: str | None = None, through: str | None = None) -> list[GateOutcome]:
    """Run gates in order. Entry criterion: the previous gate advanced (this run, or a prior recorded run)."""
    ids = [g.id for g in gates]
    lo = ids.index(start) if start else 0
    hi = ids.index(through) + 1 if through else len(gates)

    previous = load_previous()
    if lo > 0:
        prior = previous.get(ids[lo - 1])
        if not prior or prior["decision"] not in (Decision.GO.value, Decision.CONDITIONAL_GO.value):
            raise SystemExit(f"Entry criteria not met: {ids[lo - 1]} has no recorded GO. Run it first.")

    outcomes: list[GateOutcome] = []
    blocked = False
    for gate in gates[lo:hi]:
        if blocked:
            outcomes.append(GateOutcome(gate.id, gate.phase, Decision.NOT_RUN))
            continue
        print(f"\n▶ {gate.id} · {gate.phase}")
        outcome = evaluate_gate(gate)
        for c in outcome.checks:
            mark = "✅" if c.passed else ("❌" if c.blocking else "⚠️ ")
            kind = "blocking" if c.blocking else "advisory"
            print(f"   {mark} [{kind}] {c.name} ({c.seconds}s)\n        {c.evidence}")
        print(f"   ⇒ {outcome.decision.value}")
        outcomes.append(outcome)
        blocked = not outcome.advances

    _persist(outcomes, previous)
    return outcomes


def _persist(outcomes: list[GateOutcome], previous: dict[str, dict]) -> None:
    for o in outcomes:
        if o.decision is not Decision.NOT_RUN:
            previous[o.id] = {**asdict(o), "decision": o.decision.value}
    ordered = [previous[k] for k in sorted(previous)]
    REPORT_JSON.parent.mkdir(exist_ok=True)
    REPORT_JSON.write_text(json.dumps({"gates": ordered}, indent=2))

    lines = ["# Gate Decision Log", "",
             "Generated by `python -m gates`. The latest decision for each gate is shown.", "",
             "| Gate | Phase | Decision | Checks passed | Timestamp (UTC) |", "|---|---|---|---|---|"]
    for g in ordered:
        passed = sum(c["passed"] for c in g["checks"])
        row = [g["id"], g["phase"], f"**{g['decision']}**", f"{passed}/{len(g['checks'])}", g["timestamp"]]
        lines.append("| " + " | ".join(row) + " |")
    for g in ordered:
        lines += ["", f"## {g['id']} · {g['phase']} — {g['decision']}", ""]
        for c in g["checks"]:
            mark = "PASS" if c["passed"] else "FAIL"
            kind = "blocking" if c["blocking"] else "advisory"
            lines.append(f"- **{mark}** ({kind}) {c['name']}: {c['evidence']}")
    GATE_LOG_MD.write_text("\n".join(lines) + "\n")
